"use client";

import React from "react";
import { Lightbulb, Sparkles } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface QuerySuggestionsProps {
	suggestions: string[];
	thematic?: string;
	onSelectSuggestion: (suggestion: string) => void;
	isLoading?: boolean;
}

/**
 * Query Suggestions Component
 *
 * Displays contextual follow-up questions as clickable buttons
 * Generated by the RAG system based on conversation context
 */
export default function QuerySuggestions({
	suggestions,
	thematic,
	onSelectSuggestion,
	isLoading = false,
}: QuerySuggestionsProps) {
	if (!suggestions || suggestions.length === 0) return null;

	// Thematic colors
	const thematicColors: Record<string, { bg: string; border: string; icon: string }> = {
		ai_services: {
			bg: "bg-blue-50 dark:bg-blue-950/30",
			border: "border-blue-200 dark:border-blue-800",
			icon: "text-blue-600 dark:text-blue-400",
		},
		chatbot: {
			bg: "bg-purple-50 dark:bg-purple-950/30",
			border: "border-purple-200 dark:border-purple-800",
			icon: "text-purple-600 dark:text-purple-400",
		},
		rag_systems: {
			bg: "bg-green-50 dark:bg-green-950/30",
			border: "border-green-200 dark:border-green-800",
			icon: "text-green-600 dark:text-green-400",
		},
		multi_agent: {
			bg: "bg-orange-50 dark:bg-orange-950/30",
			border: "border-orange-200 dark:border-orange-800",
			icon: "text-orange-600 dark:text-orange-400",
		},
		general: {
			bg: "bg-gray-50 dark:bg-gray-950/30",
			border: "border-gray-200 dark:border-gray-800",
			icon: "text-gray-600 dark:text-gray-400",
		},
	};

	const colors = thematic && thematicColors[thematic] ? thematicColors[thematic] : thematicColors.general;

	return (
		<motion.div
			initial={{ opacity: 0, y: 10 }}
			animate={{ opacity: 1, y: 0 }}
			transition={{ duration: 0.3 }}
			className={`mt-4 p-4 rounded-lg border ${colors.bg} ${colors.border}`}
		>
			{/* Header */}
			<div className="flex items-center gap-2 mb-3">
				<Lightbulb className={`w-4 h-4 ${colors.icon}`} />
				<span className="text-sm font-medium text-gray-700 dark:text-gray-300">
					Suggested questions
				</span>
				{thematic && thematic !== "general" && (
					<span className={`text-xs px-2 py-0.5 rounded-full ${colors.bg} ${colors.border} border`}>
						{thematic.replace(/_/g, " ")}
					</span>
				)}
			</div>

			{/* Suggestions Grid */}
			<div className="space-y-2">
				<AnimatePresence>
					{suggestions.map((suggestion, index) => (
						<motion.button
							key={index}
							initial={{ opacity: 0, x: -10 }}
							animate={{ opacity: 1, x: 0 }}
							transition={{ delay: index * 0.05 }}
							whileHover={{ x: 4, scale: 1.01 }}
							whileTap={{ scale: 0.98 }}
							onClick={() => onSelectSuggestion(suggestion)}
							disabled={isLoading}
							className={`
								w-full text-left px-4 py-3 rounded-md
								bg-white dark:bg-gray-900/50
								border ${colors.border}
								hover:${colors.bg}
								transition-all duration-200
								disabled:opacity-50 disabled:cursor-not-allowed
								group
							`}
						>
							<div className="flex items-start gap-3">
								<Sparkles className={`w-4 h-4 mt-0.5 ${colors.icon} opacity-60 group-hover:opacity-100 transition-opacity`} />
								<span className="text-sm text-gray-700 dark:text-gray-300 group-hover:text-gray-900 dark:group-hover:text-gray-100">
									{suggestion}
								</span>
							</div>
						</motion.button>
					))}
				</AnimatePresence>
			</div>

			{/* Footer hint */}
			<p className="text-xs text-gray-500 dark:text-gray-500 mt-3 text-center">
				Click a question to continue the conversation
			</p>
		</motion.div>
	);
}
